// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the code between BEGIN USER CODE and END USER CODE
// Other code you write will be lost the next time you deploy the project.

/**
 * @returns {boolean}
 */
function IsCellularConnection() {
	// BEGIN USER CODE
    const NetInfo = require("@react-native-community/netinfo/lib/commonjs");
    return NetInfo.fetch().then((info) => info.type === "cellular");
	// END USER CODE
}